### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by kaicataldo** [prettier/prettier-browser-extension#318]
I'd like to propose we create a `main` branch and make that the default branch in this repository.

**Comment by nickmccurdy** [comment]
FWIW, GitHub seems to officially recommend waiting until later this year when they will add tools to automate the process: https://github.com/github/renaming#later-this-year

**Comment by nickmccurdy** [comment]
We'll need to update all of our pull request targets and the branch protection rules for master if we don't wait until it's automated. In my experience retargetting a pull request can partially break reviews. Can we wait until we have more merged first?

**Comment by kaicataldo** [comment]
After waiting a while without further PRs being landed, this is now done. We now have parody with the main `prettier/prettier` repository.

**Comment by nickmccurdy** [comment]
For future reference, GitHub now supports branch renaming, so now you can easily rename `master` to `main` without worrying about breaking PRs (they will re-track the new `main` branch automatically).

**Comment by kaicataldo** [comment]
Yup, that's what I used!
